name: Python-Lite

channels:
  - conda-forge
      
dependencies:
  - python={{ python_version }}
  - numpy
  - scipy
  - scikit-image
  - pandas
  - opencv
  - joblib
  - matplotlib-base
  - pip:
    - napari[all]
    - spyder