name:
  - Python-Lite

channels:
  - conda-forge

dependencies:
  # conda_core
  - python=3.10
  - numpy=1.24*
  - numba
  - scipy
  - pandas
  - scikit-image
  - opencv
  - scikit-learn
  - joblib
  - matplotlib-base
  - pip
  # conda_spec
  - spyder
  - pip:
    # pip_core
    - napari[all]
    # pip_spec