channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy=1.24*
  - numba
  - scipy
  - pandas
  - scikit-image
  - opencv
  - scikit-learn
  - joblib
  - matplotlib-base
  - cudatoolkit=11.2
  - cudnn=8.1
  - pyyaml
  - spyder
  - pip
  - pip:
    - napari[all]
    - albumentations
    - segmentation-models
    - tensorflow-gpu==2.10